### ISSUE TITLE
Custom CSS Sorter. Hello, could you add support for the whole document parse, please?

### ISSUE THREAD

**Issue by KostiantynO** [nacho87/custom-css-sorter#1]
Hello, could you add support for the whole document parse, please? Because currently it cuts style definitions from class selectors and pasts them at the end of CSS file :(  
But I managed to manually 💪sort whole my CSS with this tool!
I just selected each individual class and formatted it with this tool! Thank you for that!

![Custom CSS sort cuts all attributes to the end of the CSS file](https://user-images.githubusercontent.com/61573649/122595917-c9c5d700-d071-11eb-81f6-38c0515c2afb.png)

**Comment by nacho87** [comment]
Hello @KostiantynO, sorry for the delay, I will start working on this feature.

**Comment by nacho87** [comment]
With the last update I added this funcionality
